SAHAM/SAHAM/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("sahamapp.urls"))
    
]

SAHAM/sahamapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = "sahamapp"

urlpatterns = [
    path("",views.homePage, name='index'),
    path("FreelancerRegister",views.registerFreelancer, name="registerFL"),
    path("FreelancerLogin", views.loginFreelancer, name='loginFL'),
    path("FreeLancerEdit/<str:freelancerId>", views.editpage, name='editFL'),
    path('FreeLancerAddService/<str:freelancerId>', views.addService, name='addServiceFL'),
    path("DeleteService/<str:serviceId>" , views.deleteService, name='deleteService'),
    path("EditService/<str:serviceId>" , views.editService, name='editService'),
    path("CustomerLogin", views.loginCustomer, name='loginC'),
    path("CustomerRegister",views.registerCustomer, name="registerC"),
    path("FavoriteServices/<str:customerId>", views.editpage, name='favoriteServices'),
    path("ShowService/<str:username>/<str:serviceId>" , views.showService, name='showService'),
    path("ShowServices/<str:username>", views.showServices, name='showServices'),
    path("BookService/<str:username>/<str:serviceId>" , views.showService, name='bookService'),
    path("BookedServices/<str:username>", views.bookedServices, name='bookedServices')
]

SAHAM/sahamapp/models.py
from django.db import models
from django.core.validators import MinLengthValidator # This function makes sure the data field is not less than a number we specify



class Freelancer(models.Model):
    freelancerId = models.CharField(max_length=6,primary_key=True)
    email = models.EmailField(max_length=256,unique=True)
    password = models.CharField(max_length=32, validators=[MinLengthValidator(6)])
    description = models.CharField(max_length=500)
    name = models.CharField(max_length=32, validators=[MinLengthValidator(3)])
    phonenumber = models.CharField(max_length=10, validators=[MinLengthValidator(10)])


class Service(models.Model):
    serviceId = models.CharField(max_length=6, primary_key=True)
    name = models.CharField(max_length=32, validators=[MinLengthValidator(3)])
    description = models.CharField(max_length=500)
    price = models.FloatField()
    freelancer = models.ForeignKey(Freelancer, on_delete=models.CASCADE, related_name='services')


class Customer(models.Model): # 
    userName = models.CharField(max_length=32,primary_key=True, validators=[MinLengthValidator(3)])
    password = models.CharField(max_length=32, validators=[MinLengthValidator(6)])
    bookedServices = models.ManyToManyField(Service, blank=True, related_name="customers")

SAHAM/sahamapp/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect,reverse, get_object_or_404
from .models import Service,Freelancer,Customer
from django import forms
import random
import string


def generateUniqueIdProvider():
    length = 6
    characters = string.ascii_letters + string.digits
    while True:
        new_id = ''.join(random.choices(characters, k=length))
        if not Freelancer.objects.filter(freelancerId=new_id).exists():
            return new_id
        
def generateUniqueIdService():
    length = 6
    characters = string.ascii_letters + string.digits
    while True:
        new_id = ''.join(random.choices(characters, k=length))
        if not Service.objects.filter(serviceId=new_id).exists():
            return new_id
        
    

def homePage(request):
    return render(request,"sahamapp/index.html")



def registerFreelancer(request):
    if request.method == "POST":
        form = request.POST
        freelancer = Freelancer(freelancerId = generateUniqueIdProvider(),
                                email = form["email"],
                                password = form["password"],
                                description = form["description"],
                                name = form["username"],
                                phonenumber = form["phonenumber"])
        freelancer.save()
        return render(request, 'sahamapp/loginFL.html', {
            'registrationComplete': True
        })
    return render(request,'sahamapp/registerFL.html')


def loginFreelancer(request):
    if request.method == "POST":
        form = request.POST
        current = Freelancer.objects.filter(email = form["email"])
        print(current)
        if current.exists():
            if current[0].password == form["password"]:
                return redirect(reverse('sahamapp:editFL', kwargs={'freelancerId': current[0].freelancerId}))
        return render(request, "sahamapp/loginFL.html",{
            'error':True})   
    return render(request , "sahamapp/loginFL.html")

def editpage(request, freelancerId):
 
 
    freelancer = get_object_or_404(Freelancer, pk=freelancerId)
    services = Service.objects.filter(freelancer=freelancer)
    return render(request, 'sahamapp/editPage.html', {
        'services': services,
        'freelancer': freelancer
    })


def addService(request, freelancerId):
    freelancer = get_object_or_404(Freelancer, pk=freelancerId)
    if request.method == "POST":
        form = request.POST
        Service.objects.create(
            serviceId= generateUniqueIdService(),
            name= form.get("serviceName"),
            description= form.get("serviceDescription"),
            price=form.get("price"),
            freelancer=freelancer)
        return redirect(reverse('sahamapp:editFL', kwargs={"freelancerId":freelancerId}))
    else:
        return render(request, 'sahamapp/addService.html', {'freelancer': freelancer})
    
def deleteService(request, serviceId):
    freelancer = Service.objects.filter(serviceId=serviceId)[0].freelancer
    Service.objects.get(serviceId=serviceId).delete()
    return redirect(reverse('sahamapp:editFL', kwargs={'freelancerId': freelancer.freelancerId}))

def editService(request, serviceId):
    service = Service.objects.filter(serviceId=serviceId)[0]
    if request.method == "POST":
        form = request.POST

        freelancer = Service.objects.filter(serviceId=serviceId)[0].freelancer
        service.name = form.get("serviceName")
        service.description = form.get("serviceDescription")
        service.price=form.get("price")
        service.save()
        return redirect(reverse('sahamapp:editFL', kwargs={'freelancerId': freelancer.freelancerId}))
    return render(request, 'sahamapp/editService.html', {'serviceId': serviceId, 'service':service})


# Customer views

def loginCustomer(request):
    if request.method == "POST":
        form = request.POST
        current = Customer.objects.filter(userName = form["username"])
        if current.exists():
            if current[0].password == form["password"]:
                return redirect(reverse('sahamapp:showServices', kwargs={'username': current[0].userName}))
        return render(request, "sahamapp/loginC.html",{
                'error':True})
    return render(request , "sahamapp/loginC.html")

def registerCustomer(request):
    if request.method == "POST":
        form = request.POST
        existing = Customer.objects.filter(userName = form["username"]).exists()
        if existing :
                    return render(request, 'sahamapp/registerC.html', {
            'UsernameUsed': True
        })
        customer = Customer(userName = form["username"],
                                password = form["password"])
        customer.save()
        return render(request, 'sahamapp/loginC.html', {
            'registrationComplete': True
        })
    return render(request,'sahamapp/registerC.html')

def showServices(request, username):
    services = Service.objects.all()
    return render(request, 'sahamapp/showServices.html', {
        'services': services,
        'username': username
    })
def showService(request, username, serviceId):
    service = Service.objects.filter(serviceId=serviceId)[0]
    if request.method == "POST":
        Customer.objects.get(userName=username).bookedServices.add(service)
        return redirect(reverse('sahamapp:bookedServices', kwargs = {'username': username}))
    return render(request, 'sahamapp/showService.html', {'username': username, 'service':service})

def bookedServices(request, username):
    customer = get_object_or_404(Customer, userName=username)
    services = customer.bookedServices.all()
    return render(request, 'sahamapp/bookedServices.html', {
        'services': services,
        'username': username
    })

SAHAM/sahamapp/templates/sahamapp/addService.html
{% extends 'sahamapp/layout.html' %}
{% load static %}
{% block body %}
<div class="addService-container">
    <h1 class="heading">Add Service</h1>
    <form class="form-el" id="addServiceForm" novalidate action="{% url 'sahamapp:addServiceFL' freelancer.freelancerId %}" method="post">
        {% csrf_token %}
        <input placeholder="Service Name" type="text" name="serviceName" id="serviceName" required>
        <input placeholder="Describe Your Service" type="text" name="serviceDescription" id="serviceDescription" required>
        <input placeholder="Enter the Price" type="number" name="price" id="price" required>
        
        <div class="btn-container">
            <button class="btn" type="submit">Add</button>
            <a href="{% url 'sahamapp:editFL' freelancer.freelancerId %}">
                <button class="btn" type="button">Back To Profile</button>
            </a>
        </div>
    </form>
</div>

<script src="{% static 'sahamapp/scripts/addService.js' %}"></script>
{% endblock %}

SAHAM/sahamapp/templates/sahamapp/bookedServices.html
{% extends 'sahamapp/layout.html' %}
{% load static %}
{% block body %}
<div class="services-container">
    <h1 class="heading">Booked services:</h1>
    <div class="service-wrapper">
        {% for service in services %}
    <div class="service-el">
        <h2 class="details-heading">{{service.freelancer.name}}</h2>
        <h3 class="details-heading">{{service.name}}</h3>
        <h6 class="details-heading">{{service.price}} SAR</h6>
        <div class="btn-container btn-detailsservice">
            <a href="{% url 'sahamapp:showService' username service.serviceId  %}"><button class="btn" type="button">Details</button></a>
        </div>
       

    </div>
    {%endfor%}
    <a href="{% url 'sahamapp:showServices' username %}" class="button-back-services">
        <button class="btn btn-bookservice" type="button">Back to Services</button>
    </a>
    </div>

</div>

{% endblock %}

SAHAM/sahamapp/templates/sahamapp/editPage.html
{% extends 'sahamapp/layout.html' %}
{% load static %}
{% block body %}
<div class="edit-container">
    <div class="header">
        <h1 style="margin: 0; color: white; font-weight: bold;">Your services:</h1> 
        <a href="{% url 'sahamapp:index' %}" >
            <button class="btn btn-bookservice" type="button">Log Out</button>
        </a>
    </div>
    <div class="service-wrapper">
        {% for service in services %}
    <div class="service-el">
        <h3>{{service.name}}</h3>
        <h5>{{service.description}}</h5>
        <h6>{{service.price}} SAR</h6>
        <div class="btn-container">
            <a href="{% url 'sahamapp:deleteService' service.serviceId %}"><button  class="btn" type="button" >Delete</button></a>
            <a href="{% url 'sahamapp:editService' service.serviceId %}"><button class="btn" type="button">Edit</button></a>
        </div>
       

    </div>
    {%endfor%}
    </div>
   
    <a href="{% url 'sahamapp:addServiceFL' freelancer.freelancerId %}"><button class="btn btn-center" type="button">Add Service</button></a>

</div>

{% endblock %}

SAHAM/sahamapp/templates/sahamapp/editService.html
{% extends 'sahamapp/layout.html' %}
{% load static %}
{% block body %}
<div class="editService-container">
    <h1 class="heading">Edit Service</h1>
    <form class="form-el" id="editServiceForm" novalidate action="{% url 'sahamapp:editService' service.serviceId %}" method="post">
        {% csrf_token %}
        <input placeholder="Service Name" type="text" name="serviceName" id="serviceName" value="{{ service.name }}" required>
        <input placeholder="Describe Your Service" type="text" name="serviceDescription" id="serviceDescription" value="{{ service.description }}" required>
        <input placeholder="Enter the Price" type="number" name="price" id="price" value="{{ service.price }}" required>
        
        <div class="btn-container">
            <button class="btn" type="submit">Submit</button>
            <a href="{% url 'sahamapp:editFL' service.freelancer.freelancerId %}">
                <button class="btn" type="button">Back To Profile</button>
            </a>
        </div>
    </form>
</div>

<script src="{% static 'sahamapp/scripts/editService.js' %}"></script>

{% endblock %}

SAHAM/sahamapp/templates/sahamapp/index.html
{% extends 'sahamapp/layout.html' %}
{% block body%}
<div class="homepage-container">
    <div class="welcome-container"> 
        <h1 class="homepage-heading">Welcome to Saham</h1>
        <p>Are You A <a href="{%url 'sahamapp:loginC'%}" class="customer-anchor">Customer</a> or A <a href="{%url 'sahamapp:loginFL'%}" class="freelancer-anchor">Freelancer</a> ?</p>
    </div>
   
</div>
{% endblock %}

SAHAM/sahamapp/templates/sahamapp/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Saham</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'sahamapp/index.css' %}">
</head>

<body>
 {% block body %}
 {% endblock %}


</body>

</html>

SAHAM/sahamapp/templates/sahamapp/loginC.html
{% extends 'sahamapp/layout.html' %}
{% load static %}
{% block body %}
<div class="login-container">
    <h1 class="heading">Login</h1>
    <form class="form-el" id="LoginForm" novalidate action="{%url 'sahamapp:loginC'%}" method="post">
        {% csrf_token %}
        <input placeholder="Username" type="text" name="username" id="username" required>
        <input placeholder="Password" type="password" name="password" id="password" required>
        <div class="btn-container">
            <button class="btn" type="submit">Login</button>
            <a href="{% url 'sahamapp:registerC' %}"><button class="btn" type="button" >Create Account</button></a> 
        </div>
        <a href="{% url 'sahamapp:index' %}" class="btn-detailsservice">
            <button class="btn btn-bookservice" type="button">Back to Main Menu</button>
        </a>
    </form>
    {% if error %}
        <script>addEventListener("DOMContentLoaded", (event) => {alert("Email/Password incorrect")})</script>
    {% endif %}
    {% if registrationComplete %}
    <script>addEventListener("DOMContentLoaded", (event) => {alert("Registration Complete, Please Log in")})</script>
    {% endif %}
</div>

{% endblock %}

SAHAM/sahamapp/templates/sahamapp/loginFL.html
{% extends 'sahamapp/layout.html' %}
{% load static %}
{% block body %}
<div class="login-container">
    <h1 class="heading">Login</h1>
    <form class="form-el" id="LoginForm" novalidate action="{%url 'sahamapp:loginFL'%}" method="post">
        {% csrf_token %}
        <input placeholder="E-mail" type="email" name="email" id="email" required>
        <input placeholder="Password" type="password" name="password" id="password" required>
        <div class="btn-container">
            <button class="btn" type="submit">Login</button>
            <a href="{% url 'sahamapp:registerFL'%}"><button class="btn" type="button" >Create Account</button></a> 
        </div>
        <a href="{% url 'sahamapp:index' %}" class="btn-detailsservice">
            <button class="btn btn-bookservice" type="button">Back to Main Menu</button>
        </a>
    </form>
    {% if error %}
        <script>addEventListener("DOMContentLoaded", (event) => {alert("Email/Password incorrect")});</script>
    {% endif %}
    {% if registrationComplete %}
    <script>addEventListener("DOMContentLoaded", (event) => {alert("Registration Complete, Please Log in")})</script>
    {% endif %}
</div>

{% endblock %}

SAHAM/sahamapp/templates/sahamapp/registerC.html
{% extends 'sahamapp/layout.html' %}
{% load static %}
{% block body %}
<div class="register-container" id="Customer-Register">
    <h1 class="heading">Registration</h1>
    <form class="form-el" id="registrationForm" novalidate action="{%url 'sahamapp:registerC'%}" method="post">
        {% csrf_token %}
        <input placeholder="Username" type="text" name="username" id="username" required>
        <input placeholder="Password" type="password" name="password" id="password" required>
        <div class="btn-container">
            <button class="btn" type="submit">Register</button>
           <a href="{% url 'sahamapp:loginC'%}"><button class="btn" type="button" onclick="location.href='/login'">Login Instead</button></a>
           
        </div>
    </form>
</div>
    {% if UsernameUsed %}
    <script>addEventListener("DOMContentLoaded", (event) => {alert("Username Already Used")})</script>
    {% endif %}
<script src="{% static 'sahamapp/scripts/registerC.js' %}"></script>
{% endblock %}

SAHAM/sahamapp/templates/sahamapp/registerFL.html
{% extends 'sahamapp/layout.html' %}
{% load static %}
{% block body %}
<div class="register-container">
    <h1 class="heading">Registration</h1>
    <form class="form-el" id="registrationForm" novalidate action="{%url 'sahamapp:registerFL'%}" method="post">
        {% csrf_token %}
        <input placeholder="E-mail" type="email" name="email" id="email" required>
        <input placeholder="Password" type="password" name="password" id="password" required>
        <input placeholder="Username" type="text" name="username" id="username" required>
        <input placeholder="Describe Your Page" type="text" name="description" id="description" required>
        <input placeholder="Phone Number ex: 05XXXXXXXX or 009665XXXXXXXX" pattern="(?:\+?0*?966)?0?5[0-9]{8}" type="text" name="phonenumber" id="phonenumber" required oninvalid="this.setCustomValidity('Make sure the format is a valid Saudi Arabian phone number')" oninput="setCustomValidity('')">
        <div class="btn-container">
            <button class="btn" type="submit">Register</button>
           <a href="{% url 'sahamapp:loginFL'%}"> <button class="btn" type="button" onclick="location.href='/login'">Login Instead</button></a>
           
        </div>
    </form>
</div>

<script src="{% static 'sahamapp/scripts/registerFL.js' %}"></script>
{% endblock %}

SAHAM/sahamapp/templates/sahamapp/showService.html
{% extends 'sahamapp/layout.html' %}
{% load static %}
{% block body %}
<div class="showService-container" id="show-services" >
    <h1 class="details-heading" id="service-details">Service Details</h1>
    <h3 class="details-heading">Freelancer: {{service.freelancer.name}}</h3>
    <h3 class="details-heading">Service: {{service.name}}</h3>
    <h3 class="details-heading">Description: {{service.description}}</h3>
    <h3 class="details-heading">Price: {{service.price}} SAR</h3>
        <div class="btn-container">
    <form class="form-el" id="editServiceForm" novalidate action="{% url 'sahamapp:showService' username service.serviceId %}" method="post">
    {% csrf_token %}
    <div class="btn-divs">
    <button class="btn button-center-service" type="submit">Book Service</button>
    <a href="{% url 'sahamapp:showServices' username %}">
        <button class="btn button-center-service" type="button">Back to Services</button>
    </a>
    </div>
    </form>
            

        </div>

</div>

<script src="{% static 'sahamapp/scripts/editService.js' %}"></script>

{% endblock %}

SAHAM/sahamapp/templates/sahamapp/showServices.html
{% extends 'sahamapp/layout.html' %}
{% load static %}
{% block body %}
<div class="services-container">
    <div class="header">
        <h1 style="margin: 0; color: white; font-weight: bold;">Available services:</h1>
        <a href="{% url 'sahamapp:bookedServices' username %}" >
            <button class="btn btn-bookservice" type="button">Booked Services</button>
        </a>
        <a href="{% url 'sahamapp:index' %}" >
            <button class="btn btn-bookservice" type="button">Log Out</button>
        </a>
    </div>
    <div class="service-wrapper">
        {% for service in services %}
    <div class="service-el">
        <h2 class="details-heading">{{service.freelancer.name}}</h2>
        <h3 class="details-heading">{{service.name}}</h3>
        <h6 class="details-heading">{{service.price}} SAR</h6>
        <div class="btn-container btn-detailsservice">
            <a href="{% url 'sahamapp:showService' username service.serviceId  %}"><button class="btn" type="button">Details</button></a>
        </div>
    </div>
    {%endfor%}
    </div>

</div>

{% endblock %}